let name="Rahul";
let school="Royal Public School";
let grade="6th";
let section="A"
let rollno="10";
let marks_english=88;
let marks_maths=76;
let marks_science=98;
console.log("=================================================================================");
console.log("||                                                                             ||");
console.log("||                                                                             ||");
console.log("||                                                                             ||");
console.log("||                      ***    "+school +"   ***                       ||");
console.log("||                                                                             ||");
console.log("||                                REPORT CARD                                  ||");
console.log("||                                                                             ||");
console.log("||                                                                             ||");
console.log("||     Name      :  "+name +"                                 Rollno   :  "+rollno +"       ||");
console.log("||                                                                             ||");
console.log("||     Grade     :  "+grade +"                                                        ||" );
console.log("||                                                                             ||");
console.log("||     Section   :  "+section +"                                                          ||");
console.log("||                                                                             ||");
console.log("||                                                                             ||");
console.log("||                                                                             ||");
console.log("||            °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°            ||");
console.log("||            °           SUBJECT        °          MARKS         °            ||");
console.log("||            °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°            ||");
console.log("||            °           English       °          "+ marks_english +"             °            ||");
console.log("||            °           Maths         °          "+ marks_maths + "             °            ||");
console.log("||            °           Science       °          "+ marks_science +"             °            ||");
console.log("||            °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°            ||");
console.log("||                                                                             ||");
console.log("||            :PASS                                                            ||");
console.log("||                                                                             ||");
console.log("||                                                                             ||");
console.log("||                                                                             ||");
console.log("=================================================================================");
